### PR TITLE
fix duration export to only export full weeks as nW

### PR DESCRIPTION
**Pull request by ralfbecker**
as https://tools.ietf.org/html/rfc5545#section-3.3.6 does not allow to mix weeks with days, hours, ...

### CODE REVIEW

**Comment by ralfbecker** [comment]
Any news?

I'd like to get ride again of our forked class.

Ralf

**Comment by yunosh** [comment]
Thanks!

**Comment by ralfbecker** [comment]
Hi Jan, 

do you mind tagging a new release, just accepting the pull request does not create a new package on composer (apart from the master).

Ralf

**Comment by ralfbecker** [comment]
Any news about a new release containing that fix?

Or even better Horde packages available via Composer ;)

Ralf

**Pull request merged**
